### ISSUE TITLE
Running preview/record should not save config

### ISSUE THREAD

**Issue by privatezero** [privatezero/gui-work#23]
Currently if the user saves options and then changes options before exiting, upon relaunch of the app the correct (saved) options will be applied to the GUI.

However, if the user performs an action such as launching preview mode, the saved options will be overwritten with the current options, making the saved options not persist on relaunch.

Needs to be changed to maintain separation between saved and selected options

**Comment by ablwr** [comment]
Whoops I did that intentionally! OK will fix

**Comment by ablwr** [comment]
Status o this?

**Comment by privatezero** [comment]
Fixed in https://github.com/privatezero/gui-work/pull/32, although untested with record as the file path created by the current file browser in the GUI creates broken paths for me. Can close tho!
